#dataset_path = '../GroundTruth/LabelME/Images'
#dst_path = '../segmented/segmented_'
dataset_path = '../holidays_selection/'
#dst_path = '../segmented_holidays/segmented_'
dst_path = '../segmented3_holidays/segmented_'